




    // -------------------------------
    // Data tables & Maps
    // -------------------------------

    global.data = {

        disciplineData : [
            { id: "disciplineAbombwe",      label: "Abombwe",      img_1_src: "icon_discipline_abombwe_inferior.png",      img_2_src: "icon_discipline_abombwe_superior.png",      img_3_src: "icon_discipline_abombwe_other.png",      img_4_src: "icon_discipline_abombwe_inferior_innate.png",      img_5_src: "icon_discipline_abombwe_superior_innate.png",      img_6_src: "icon_discipline_abombwe_other_innate.png" },
            { id: "disciplineAuspex",       label: "Auspex",       img_1_src: "icon_discipline_auspex_inferior.png",       img_2_src: "icon_discipline_auspex_superior.png",       img_3_src: "icon_discipline_auspex_other.png",       img_4_src: "icon_discipline_auspex_inferior_innate.png",       img_5_src: "icon_discipline_auspex_superior_innate.png",       img_6_src: "icon_discipline_auspex_other_innate.png" },
            { id: "disciplineAnimalism",    label: "Animalism",    img_1_src: "icon_discipline_animalism_inferior.png",    img_2_src: "icon_discipline_animalism_superior.png",    img_3_src: "icon_discipline_animalism_other.png",    img_4_src: "icon_discipline_animalism_inferior_innate.png",    img_5_src: "icon_discipline_animalism_superior_innate.png",    img_6_src: "icon_discipline_animalism_other_innate.png" },
            { id: "disciplineCelerity",     label: "Celerity",     img_1_src: "icon_discipline_celerity_inferior.png",     img_2_src: "icon_discipline_celerity_superior.png",     img_3_src: "icon_discipline_celerity_other.png",     img_4_src: "icon_discipline_celerity_inferior_innate.png",     img_5_src: "icon_discipline_celerity_superior_innate.png",     img_6_src: "icon_discipline_celerity_other_innate.png" },
            { id: "disciplineChimerstry",   label: "Chimerstry",   img_1_src: "icon_discipline_chimerstry_inferior.png",   img_2_src: "icon_discipline_chimerstry_superior.png",   img_3_src: "icon_discipline_chimerstry_other.png",   img_4_src: "icon_discipline_chimerstry_inferior_innate.png",   img_5_src: "icon_discipline_chimerstry_superior_innate.png",   img_6_src: "icon_discipline_chimerstry_other_innate.png" },
            { id: "disciplineDaimonion",    label: "Daimonion",    img_1_src: "icon_discipline_daimonion_inferior.png",    img_2_src: "icon_discipline_daimonion_superior.png",    img_3_src: "icon_discipline_daimonion_other.png",    img_4_src: "icon_discipline_daimonion_inferior_innate.png",    img_5_src: "icon_discipline_daimonion_superior_innate.png",    img_6_src: "icon_discipline_daimonion_other_innate.png" },
            { id: "disciplineDementation",  label: "Dementation",  img_1_src: "icon_discipline_dementation_inferior.png",  img_2_src: "icon_discipline_dementation_superior.png",  img_3_src: "icon_discipline_dementation_other.png",  img_4_src: "icon_discipline_dementation_inferior_innate.png",  img_5_src: "icon_discipline_dementation_superior_innate.png",  img_6_src: "icon_discipline_dementation_other_innate.png" },
            { id: "disciplineDominate",     label: "Dominate",     img_1_src: "icon_discipline_dominate_inferior.png",     img_2_src: "icon_discipline_dominate_superior.png",     img_3_src: "icon_discipline_dominate_other.png",     img_4_src: "icon_discipline_dominate_inferior_innate.png",     img_5_src: "icon_discipline_dominate_superior_innate.png",     img_6_src: "icon_discipline_dominate_other_innate.png" },
            { id: "disciplineFortitude",    label: "Fortitude",    img_1_src: "icon_discipline_fortitude_inferior.png",    img_2_src: "icon_discipline_fortitude_superior.png",    img_3_src: "icon_discipline_fortitude_other.png",    img_4_src: "icon_discipline_fortitude_inferior_innate.png",    img_5_src: "icon_discipline_fortitude_superior_innate.png",    img_6_src: "icon_discipline_fortitude_other_innate.png" },
            { id: "disciplineMaleficia",    label: "Maleficia",    img_1_src: "icon_discipline_maleficia_inferior.png",    img_2_src: "icon_discipline_maleficia_superior.png",    img_3_src: "icon_discipline_maleficia_other.png",    img_4_src: "icon_discipline_maleficia_inferior_innate.png",    img_5_src: "icon_discipline_maleficia_superior_innate.png",    img_6_src: "icon_discipline_maleficia_other_innate.png" },
            { id: "disciplineMelpominee",   label: "Melpominee",   img_1_src: "icon_discipline_melpominee_inferior.png",   img_2_src: "icon_discipline_melpominee_superior.png",   img_3_src: "icon_discipline_melpominee_other.png",   img_4_src: "icon_discipline_melpominee_inferior_innate.png",   img_5_src: "icon_discipline_melpominee_superior_innate.png",   img_6_src: "icon_discipline_melpominee_other_innate.png" },
            { id: "disciplineMytherceria",  label: "Mytherceria",  img_1_src: "icon_discipline_mytherceria_inferior.png",  img_2_src: "icon_discipline_mytherceria_superior.png",  img_3_src: "icon_discipline_mytherceria_other.png",  img_4_src: "icon_discipline_mytherceria_inferior_innate.png",  img_5_src: "icon_discipline_mytherceria_superior_innate.png",  img_6_src: "icon_discipline_mytherceria_other_innate.png" },
            { id: "disciplineNecromancy",   label: "Necromancy",   img_1_src: "icon_discipline_necromancy_inferior.png",   img_2_src: "icon_discipline_necromancy_superior.png",   img_3_src: "icon_discipline_necromancy_other.png",   img_4_src: "icon_discipline_necromancy_inferior_innate.png",   img_5_src: "icon_discipline_necromancy_superior_innate.png",   img_6_src: "icon_discipline_necromancy_other_innate.png" },
            { id: "disciplineObeah",        label: "Obeah",        img_1_src: "icon_discipline_obeah_inferior.png",        img_2_src: "icon_discipline_obeah_superior.png",        img_3_src: "icon_discipline_obeah_other.png",        img_4_src: "icon_discipline_obeah_inferior_innate.png",        img_5_src: "icon_discipline_obeah_superior_innate.png",        img_6_src: "icon_discipline_obeah_other_innate.png" },
            { id: "disciplineObfuscate",    label: "Obfuscate",    img_1_src: "icon_discipline_obfuscate_inferior.png",    img_2_src: "icon_discipline_obfuscate_superior.png",    img_3_src: "icon_discipline_obfuscate_other.png",    img_4_src: "icon_discipline_obfuscate_inferior_innate.png",    img_5_src: "icon_discipline_obfuscate_superior_innate.png",    img_6_src: "icon_discipline_obfuscate_other_innate.png" },
            { id: "disciplineOblivion",     label: "Oblivion",     img_1_src: "icon_discipline_oblivion_inferior.png",     img_2_src: "icon_discipline_oblivion_superior.png",     img_3_src: "icon_discipline_oblivion_other.png",     img_4_src: "icon_discipline_oblivion_inferior_innate.png",     img_5_src: "icon_discipline_oblivion_superior_innate.png",     img_6_src: "icon_discipline_oblivion_other_innate.png" },            
            { id: "disciplineObtenebration",label: "Obtenebration",img_1_src: "icon_discipline_obtenebration_inferior.png",img_2_src: "icon_discipline_obtenebration_superior.png",img_3_src: "icon_discipline_obtenebration_other.png",img_4_src: "icon_discipline_obtenebration_inferior_innate.png",img_5_src: "icon_discipline_obtenebration_superior_innate.png",img_6_src: "icon_discipline_obtenebration_other_innate.png" },
            { id: "disciplinePotence",      label: "Potence",      img_1_src: "icon_discipline_potence_inferior.png",      img_2_src: "icon_discipline_potence_superior.png",      img_3_src: "icon_discipline_potence_other.png",      img_4_src: "icon_discipline_potence_inferior_innate.png",      img_5_src: "icon_discipline_potence_superior_innate.png",      img_6_src: "icon_discipline_potence_other_innate.png" },
            { id: "disciplinePresence",     label: "Presence",     img_1_src: "icon_discipline_presence_inferior.png",     img_2_src: "icon_discipline_presence_superior.png",     img_3_src: "icon_discipline_presence_other.png",     img_4_src: "icon_discipline_presence_inferior_innate.png",     img_5_src: "icon_discipline_presence_superior_innate.png",     img_6_src: "icon_discipline_presence_other_innate.png" },
            { id: "disciplineProtean",      label: "Protean",      img_1_src: "icon_discipline_protean_inferior.png",      img_2_src: "icon_discipline_protean_superior.png",      img_3_src: "icon_discipline_protean_other.png",      img_4_src: "icon_discipline_protean_inferior_innate.png",      img_5_src: "icon_discipline_protean_superior_innate.png",      img_6_src: "icon_discipline_protean_other_innate.png" },
            { id: "disciplineQuietus",      label: "Quietus",      img_1_src: "icon_discipline_quietus_inferior.png",      img_2_src: "icon_discipline_quietus_superior.png",      img_3_src: "icon_discipline_quietus_other.png",      img_4_src: "icon_discipline_quietus_inferior_innate.png",      img_5_src: "icon_discipline_quietus_superior_innate.png",      img_6_src: "icon_discipline_quietus_other_innate.png" },
            { id: "disciplineSanguinus",    label: "Sanguinus",    img_1_src: "icon_discipline_sanguinus_inferior.png",    img_2_src: "icon_discipline_sanguinus_superior.png",    img_3_src: "icon_discipline_sanguinus_other.png",    img_4_src: "icon_discipline_sanguinus_inferior_innate.png",    img_5_src: "icon_discipline_sanguinus_superior_innate.png",    img_6_src: "icon_discipline_sanguinus_other_innate.png" },
            { id: "disciplineSerpentis",    label: "Serpentis",    img_1_src: "icon_discipline_serpentis_inferior.png",    img_2_src: "icon_discipline_serpentis_superior.png",    img_3_src: "icon_discipline_serpentis_other.png",    img_4_src: "icon_discipline_serpentis_inferior_innate.png",    img_5_src: "icon_discipline_serpentis_superior_innate.png",    img_6_src: "icon_discipline_serpentis_other_innate.png" },
            { id: "disciplineSpiritus",     label: "Spiritus",     img_1_src: "icon_discipline_spiritus_inferior.png",     img_2_src: "icon_discipline_spiritus_superior.png",     img_3_src: "icon_discipline_spiritus_other.png",     img_4_src: "icon_discipline_spiritus_inferior_innate.png",     img_5_src: "icon_discipline_spiritus_superior_innate.png",     img_6_src: "icon_discipline_spiritus_other_innate.png" },
            { id: "disciplineStriga",       label: "Striga",       img_1_src: "icon_discipline_striga_inferior.png",       img_2_src: "icon_discipline_striga_superior.png",       img_3_src: "icon_discipline_striga_other.png",       img_4_src: "icon_discipline_striga_inferior_innate.png",       img_5_src: "icon_discipline_striga_superior_innate.png",       img_6_src: "icon_discipline_striga_other_innate.png" },
            { id: "disciplineTemporis",     label: "Temporis",     img_1_src: "icon_discipline_temporis_inferior.png",     img_2_src: "icon_discipline_temporis_superior.png",     img_3_src: "icon_discipline_temporis_other.png",     img_4_src: "icon_discipline_temporis_inferior_innate.png",     img_5_src: "icon_discipline_temporis_superior_innate.png",     img_6_src: "icon_discipline_temporis_other_innate.png" },
            { id: "disciplineThanatosis",   label: "Thanatosis",   img_1_src: "icon_discipline_thanatosis_inferior.png",   img_2_src: "icon_discipline_thanatosis_superior.png",   img_3_src: "icon_discipline_thanatosis_other.png",   img_4_src: "icon_discipline_thanatosis_inferior_innate.png",   img_5_src: "icon_discipline_thanatosis_superior_innate.png",   img_6_src: "icon_discipline_thanatosis_other_innate.png" },
            { id: "disciplineThaumaturgy",  label: "Thaumaturgy",  img_1_src: "icon_discipline_thaumaturgy_inferior.png",  img_2_src: "icon_discipline_thaumaturgy_superior.png",  img_3_src: "icon_discipline_thaumaturgy_other.png",  img_4_src: "icon_discipline_thaumaturgy_inferior_innate.png",  img_5_src: "icon_discipline_thaumaturgy_superior_innate.png",  img_6_src: "icon_discipline_thaumaturgy_other_innate.png" },
            { id: "disciplineValeren",      label: "Valeren",      img_1_src: "icon_discipline_valeren_inferior.png",      img_2_src: "icon_discipline_valeren_superior.png",      img_3_src: "icon_discipline_valeren_other.png",      img_4_src: "icon_discipline_valeren_inferior_innate.png",      img_5_src: "icon_discipline_valeren_superior_innate.png",      img_6_src: "icon_discipline_valeren_other_innate.png" },
            { id: "disciplineVicissitude",  label: "Vicissitude",  img_1_src: "icon_discipline_vicissitude_inferior.png",  img_2_src: "icon_discipline_vicissitude_superior.png",  img_3_src: "icon_discipline_vicissitude_other.png",  img_4_src: "icon_discipline_vicissitude_inferior_innate.png",  img_5_src: "icon_discipline_vicissitude_superior_innate.png",  img_6_src: "icon_discipline_vicissitude_other_innate.png" },
            { id: "disciplineVisceratika",  label: "Visceratika",  img_1_src: "icon_discipline_visceratika_inferior.png",  img_2_src: "icon_discipline_visceratika_superior.png",  img_3_src: "icon_discipline_visceratika_other.png",  img_4_src: "icon_discipline_visceratika_inferior_innate.png",  img_5_src: "icon_discipline_visceratika_superior_innate.png",  img_6_src: "icon_discipline_visceratika_other_innate.png" }
        ],

        clanData : [
            { id: "clanAhrimanes",             label: "Ahrimanes",             imgSrc: "icon_clan_ahrimanes.png",             image: new Image() },
            { id: "clanAkunanse",              label: "Akunanse",              imgSrc: "icon_clan_akunanse.png",              image: new Image() },
            { id: "clanAnda",                  label: "Anda",                  imgSrc: "icon_clan_anda.png",                  image: new Image() },
            { id: "clanAssamite",              label: "Assamite",              imgSrc: "icon_clan_assamite.png",              image: new Image() },
            { id: "clanBaali",                 label: "Baali",                 imgSrc: "icon_clan_baali.png",                 image: new Image() },
            { id: "clanBanuHaqim",             label: "Banu Haqim",            imgSrc: "icon_clan_banu_haqim.png",            image: new Image() },
            { id: "clanBloodBrothers",         label: "Blood Brothers",        imgSrc: "icon_clan_blood_brothers.png",        image: new Image() },
            { id: "clanBrujah",                label: "Brujah",                imgSrc: "icon_clan_brujah.png",                image: new Image() },
            { id: "clanBrujahAntitribu",       label: "Brujah Antitribu",      imgSrc: "icon_clan_brujah_antitribu.png",      image: new Image() },
            { id: "clanCaitiff",               label: "Caitiff",               imgSrc: "icon_clan_caitiff.png",               image: new Image() },
            { id: "clanCappadocian",           label: "Cappadocian",           imgSrc: "icon_clan_cappadocian.png",           image: new Image() },
            { id: "clanDaughtersOfCacophony",  label: "Daughters of Cacophony",imgSrc: "icon_clan_daughters_of_cacophony.png",image: new Image() },
            { id: "clanFollowersOfSet",        label: "Followers of Set",      imgSrc: "icon_clan_followers_of_set.png",      image: new Image() },
            { id: "clanGangrel",               label: "Gangrel",               imgSrc: "icon_clan_gangrel.png",               image: new Image() },
            { id: "clanGangrelAntitribu",      label: "Gangrel Antitribu",     imgSrc: "icon_clan_gangrel_antitribu.png",     image: new Image() },
            { id: "clanGargoyles",             label: "Gargoyles",             imgSrc: "icon_clan_gargoyles.png",             image: new Image() },
            { id: "clanGiovanni",              label: "Giovanni",              imgSrc: "icon_clan_giovanni.png",              image: new Image() },
            { id: "clanGuruhi",                label: "Guruhi",                imgSrc: "icon_clan_guruhi.png",                image: new Image() },
            { id: "clanHecata",                label: "Hecata",                imgSrc: "icon_clan_hecata.png",                image: new Image() },
            { id: "clanHarbringersOfSkulls",   label: "Harbingers of Skulls",  imgSrc: "icon_clan_harbringers_of_skulls.png", image: new Image() },
            { id: "clanIshtarri",              label: "Ishtarri",              imgSrc: "icon_clan_ishtarri.png",              image: new Image() },
            { id: "clanKiasyd",                label: "Kiasyd",                imgSrc: "icon_clan_kiasyd.png",                image: new Image() },
            { id: "clanKinyonyi",              label: "Kinyonyi",              imgSrc: "icon_clan_kinyonyi.png",              image: new Image() },
            { id: "clanLamia",                 label: "Lamia",                 imgSrc: "icon_clan_lamia.png",                 image: new Image() },
            { id: "clanLasombra",              label: "Lasombra",              imgSrc: "icon_clan_lasombra.png",              image: new Image() },
            { id: "clanMalkavian",             label: "Malkavian",             imgSrc: "icon_clan_malkavian.png",             image: new Image() },
            { id: "clanMalkavianAntitribu",    label: "Malkavian Antitribu",   imgSrc: "icon_clan_malkavian_antitribu.png",   image: new Image() },
            { id: "clanMinistry",              label: "Ministry",              imgSrc: "icon_clan_ministry.png",              image: new Image() },
            { id: "clanNagaraja",              label: "Nagaraja",              imgSrc: "icon_clan_nagaraja.png",              image: new Image() },
            { id: "clanNagloper",              label: "Nagloper",              imgSrc: "icon_clan_nagloper.png",              image: new Image() },
            { id: "clanNoiad",                 label: "Noiad",                 imgSrc: "icon_clan_noiad.png",                 image: new Image() },
            { id: "clanNosferatu",             label: "Nosferatu",             imgSrc: "icon_clan_nosferatu.png",             image: new Image() },
            { id: "clanNosferatuAntitribu",    label: "Nosferatu Antitribu",   imgSrc: "icon_clan_nosferatu_antitribu.png",   image: new Image() },
            { id: "clanOsebo",                 label: "Osebo",                 imgSrc: "icon_clan_osebo.png",                 image: new Image() },
            { id: "clanPander",                label: "Pander",                imgSrc: "icon_clan_pander.png",                image: new Image() },
            { id: "clanRavnos",                label: "Ravnos",                imgSrc: "icon_clan_ravnos.png",                image: new Image() },
            { id: "clanSalubri",               label: "Salubri",               imgSrc: "icon_clan_salubri.png",               image: new Image() },
            { id: "clanSalubriAntitribu",      label: "Salubri Antitribu",     imgSrc: "icon_clan_salubri_antitribu.png",     image: new Image() },
            { id: "clanSamedi",                label: "Samedi",                imgSrc: "icon_clan_samedi.png",                image: new Image() },
            { id: "clanToreador",              label: "Toreador",              imgSrc: "icon_clan_toreador.png",              image: new Image() },
            { id: "clanToreadorAntitribu",     label: "Toreador Antitribu",    imgSrc: "icon_clan_toreador_antitribu.png",    image: new Image() },
            { id: "clanTremere",               label: "Tremere",               imgSrc: "icon_clan_tremere.png",               image: new Image() },
            { id: "clanTremereAntitribu",      label: "Tremere Antitribu",     imgSrc: "icon_clan_tremere_antitribu.png",     image: new Image() },
            { id: "clanTrueBrujah",            label: "True Brujah",           imgSrc: "icon_clan_true_brujah.png",           image: new Image() },
            { id: "clanTzimisce",              label: "Tzimisce",              imgSrc: "icon_clan_tzimisce.png",              image: new Image() },
            { id: "clanVentrue",               label: "Ventrue",               imgSrc: "icon_clan_ventrue.png",               image: new Image() },
            { id: "clanVentrueAntitribu",      label: "Ventrue Antitribu",     imgSrc: "icon_clan_ventrue_antitribu.png",     image: new Image() },
            { id: "clanVolgirre",              label: "Volgirre",              imgSrc: "icon_clan_volgirre.png",              image: new Image() }
        ],

        frameMap : {
            // Main Frame Options
            "vampire_generic_01"      : "frame_vampire_generic_01.png",
            "vampire_generic_02"      : "frame_vampire_generic_02.png",
            "vampire_generic_03"      : "frame_vampire_generic_03.png",
            "vampire_generic_04"      : "frame_vampire_generic_04.png",

            // Imbued frame
            "imbued_generic_01"       : "frame_imbued_generic_01.png",

            // Generic Library Frame Options
            "library_generic_01"      : "frame_library_generic_01.png",
            "library_generic_02"      : "frame_library_generic_02.png",  
            "library_generic_03"      : "frame_library_generic_03.png",
            "library_generic_04"      : "frame_library_generic_04.png",
            "frame_black_marble_01"   : "frame_black_marble_01.png",        

            // Clan Frame Options
            "clan_assamite"           : "frame_clan_assamite.png",
            "clan_brujah"             : "frame_clan_brujah.png",
            "clan_brujah_antitribu"   : "frame_clan_brujah_antitribu.png",
            "clan_cappadocian"        : "frame_clan_cappadocian.png",
            "clan_gangrel"            : "frame_clan_gangrel.png",
            "clan_gangrel_antitribu"  : "frame_clan_gangrel_antitribu.png",
            "clan_giovanni"           : "frame_clan_giovanni.png",
            "clan_lamia"              : "frame_clan_lamia.png",
            "clan_lasombra"           : "frame_clan_lasombra.png",
            "clan_malkavian"          : "frame_clan_malkavian.png",
            "clan_malkavian_antitribu": "frame_clan_malkavian_antitribu.png",
            "clan_nosferatu"          : "frame_clan_nosferatu.png",
            "clan_nosferatu_antitribu": "frame_clan_nosferatu_antitribu.png",
            "clan_ravnos"             : "frame_clan_ravnos.png",
            "clan_salubri"            : "frame_clan_salubri.png",
            "clan_salubri_antitribu"  : "frame_clan_salubri_antitribu.png",
            "clan_toreador"           : "frame_clan_toreador.png",
            "clan_toreador_antitribu" : "frame_clan_toreador_antitribu.png",
            "clan_tremere"            : "frame_clan_tremere.png",
            "clan_tremere_antitribu"  : "frame_clan_tremere_antitribu.png",
            "clan_tzimisce"           : "frame_clan_tzimisce.png",
            "clan_ventrue"            : "frame_clan_ventrue.png",
            "clan_ventrue_antitribu"  : "frame_clan_ventrue_antitribu.png",

            // Other Card Frame Options
            "modifier_card"           : "frame_modifier.png",
            "action_card"             : "frame_action.png",
            "political_action_card"   : "frame_political_action.png",
            "event_card"              : "frame_event.png",
            "master_card"             : "frame_master.png",
            "reaction_card"           : "frame_reaction.png",
            "combat_card"             : "frame_combat.png",
            "equipment_card"          : "frame_equipment.png",
            "ally_card"               : "frame_ally.png",

            // Side Panel Options
            "none"                          : null,
            "generic_green_marble"          : "sidepanel_generic_green_marble.png",
            "generic_black_marble"          : "sidepanel_generic_black_marble.png",
            "sidepanel_action"              : "sidepanel_action.png",
            "sidepanel_political_action"    : "sidepanel_political_action.png",
            "sidepanel_event"               : "sidepanel_event.png",
            "sidepanel_master"              : "sidepanel_master.png",
            "sidepanel_reaction"            : "sidepanel_reaction.png",
            "sidepanel_combat"              : "sidepanel_combat.png",
            "sidepanel_equipment"           : "sidepanel_equipment.png",
            "sidepanel_ally"                : "sidepanel_ally.png",
            "sidepanel_assamite"            : "sidepanel_assamite.png",
            "sidepanel_banu_haqim"          : "sidepanel_banu_haqim.png",            
            "sidepanel_brujah"              : "sidepanel_brujah.png",
            "sidepanel_brujah_antitribu"    : "sidepanel_brujah_antitribu.png",
            "sidepanel_cappadocian"         : "sidepanel_cappadocian.png",
            "sidepanel_gangrel"             : "sidepanel_gangrel.png",
            "sidepanel_gangrel_antitribu"   : "sidepanel_gangrel_antitribu.png",
            "sidepanel_giovanni"            : "sidepanel_giovanni.png",
            "sidepanel_lamia"               : "sidepanel_lamia.png",
            "sidepanel_lasombra"            : "sidepanel_lasombra.png",
            "sidepanel_malkavian"           : "sidepanel_malkavian.png",
            "sidepanel_malkavian_antitribu" : "sidepanel_malkavian_antitribu.png",
            "sidepanel_nosferatu"           : "sidepanel_nosferatu.png",
            "sidepanel_nosferatu_antitribu" : "sidepanel_nosferatu_antitribu.png",
            "sidepanel_ravnos"              : "sidepanel_ravnos.png",
            "sidepanel_salubri"             : "sidepanel_salubri.png",
            "sidepanel_salubri_antitribu"   : "sidepanel_salubri_antitribu.png",
            "sidepanel_toreador"            : "sidepanel_toreador.png",
            "sidepanel_toreador_antitribu"  : "sidepanel_toreador_antitribu.png",
            "sidepanel_tremere"             : "sidepanel_tremere.png",
            "sidepanel_tremere_antitribu"   : "sidepanel_tremere_antitribu.png",
            "sidepanel_tzimisce"            : "sidepanel_tzimisce.png",
            "sidepanel_ventrue"             : "sidepanel_ventrue.png",
            "sidepanel_ventrue_antitribu"   : "sidepanel_ventrue_antitribu.png"
        },

        typeMap : [
            { id: "card_type_action",         label: "Action",         iconSrc: "symbol_action.png" },
            { id: "card_type_reaction",       label: "Reaction",       iconSrc: "symbol_reaction.png" },
            { id: "card_type_combat",         label: "Combat",         iconSrc: "symbol_combat.png" },
            { id: "card_type_equipment",      label: "Equipment",      iconSrc: "symbol_equipment.png" },
            { id: "card_type_ally",           label: "Ally",           iconSrc: "symbol_ally.png" },
            { id: "card_type_master",         label: "Master",         iconSrc: "symbol_master.png" },
            { id: "card_type_modifier",       label: "Modifier",       iconSrc: "symbol_modifier.png" },
            { id: "card_type_retainer",       label: "Retainer",       iconSrc: "symbol_retainer.png" },
            { id: "card_type_event",          label: "Event",          iconSrc: "symbol_event.png" },
            { id: "card_type_political",      label: "Political",      iconSrc: "symbol_political.png" }
        ],

        symbolMap : {
            // Pool, Blood, Capacity, and Life
            "symbol_pool"              : "symbol_pool.png",
            "symbol_blood"             : "symbol_blood.png",
            "symbol_capacity"          : "symbol_capacity.png",
            "symbol_life"              : "symbol_life.png",

            // Other Useful Symbols
            "symbol_vote"              : "symbol_vote.png",

        },

        markdownTextMap : {
            "[b]"   : "bold",       // Bold text
            "[/b]"  : "normal",     // End bold
            "[i]"   : "italic",     // Italic text
            "[/i]"  : "normal",     // End italic
            "[n]"   : "newline"     // Newline
        },

        markdownIconMap : {
            // Disciplines
            "[abo]": "icon_discipline_abombwe_inferior.png",
            "[ABO]": "icon_discipline_abombwe_superior.png",
            "[aus]": "icon_discipline_auspex_inferior.png",
            "[AUS]": "icon_discipline_auspex_superior.png",
            "[ani]": "icon_discipline_animalism_inferior.png",
            "[ANI]": "icon_discipline_animalism_superior.png",
            "[cel]": "icon_discipline_celerity_inferior.png",
            "[CEL]": "icon_discipline_celerity_superior.png",
            "[chi]": "icon_discipline_chimerstry_inferior.png",
            "[CHI]": "icon_discipline_chimerstry_superior.png",
            "[dai]": "icon_discipline_daimonion_inferior.png",
            "[DAI]": "icon_discipline_daimonion_superior.png",
            "[dem]": "icon_discipline_dementation_inferior.png",
            "[DEM]": "icon_discipline_dementation_superior.png",
            "[dom]": "icon_discipline_dominate_inferior.png",
            "[DOM]": "icon_discipline_dominate_superior.png",
            "[for]": "icon_discipline_fortitude_inferior.png",
            "[FOR]": "icon_discipline_fortitude_superior.png",
            "[mal]": "icon_discipline_maleficia_inferior.png",
            "[MAL]": "icon_discipline_maleficia_superior.png",
            "[mel]": "icon_discipline_melpominee_inferior.png",
            "[MEL]": "icon_discipline_melpominee_superior.png",
            "[myt]": "icon_discipline_mytherceria_inferior.png",
            "[MYT]": "icon_discipline_mytherceria_superior.png",
            "[nec]": "icon_discipline_necromancy_inferior.png",
            "[NEC]": "icon_discipline_necromancy_superior.png",
            "[obe]": "icon_discipline_obeah_inferior.png",
            "[OBE]": "icon_discipline_obeah_superior.png",
            "[obf]": "icon_discipline_obfuscate_inferior.png",
            "[OBF]": "icon_discipline_obfuscate_superior.png",
            "[obl]": "icon_discipline_oblivion_inferior.png",
            "[OBL]": "icon_discipline_oblivion_superior.png",            
            "[obt]": "icon_discipline_obtenebration_inferior.png",
            "[OBT]": "icon_discipline_obtenebration_superior.png",
            "[pot]": "icon_discipline_potence_inferior.png",
            "[POT]": "icon_discipline_potence_superior.png",
            "[pre]": "icon_discipline_presence_inferior.png",
            "[PRE]": "icon_discipline_presence_superior.png",
            "[pro]": "icon_discipline_protean_inferior.png",
            "[PRO]": "icon_discipline_protean_superior.png",
            "[qui]": "icon_discipline_quietus_inferior.png",
            "[QUI]": "icon_discipline_quietus_superior.png",
            "[san]": "icon_discipline_sanguinus_inferior.png",
            "[SAN]": "icon_discipline_sanguinus_superior.png",
            "[ser]": "icon_discipline_serpentis_inferior.png",
            "[SER]": "icon_discipline_serpentis_superior.png",
            "[spi]": "icon_discipline_spiritus_inferior.png",
            "[SPI]": "icon_discipline_spiritus_superior.png",
            "[str]": "icon_discipline_striga_inferior.png",
            "[STR]": "icon_discipline_striga_superior.png",
            "[tem]": "icon_discipline_temporis_inferior.png",
            "[TEM]": "icon_discipline_temporis_superior.png",
            "[tha]": "icon_discipline_thaumaturgy_inferior.png",
            "[THA]": "icon_discipline_thaumaturgy_superior.png",
            "[thn]": "icon_discipline_thanatosis_inferior.png",
            "[THN]": "icon_discipline_thanatosis_superior.png",      
            "[val]": "icon_discipline_valeren_inferior.png",
            "[VAL]": "icon_discipline_valeren_superior.png",
            "[vic]": "icon_discipline_vicissitude_inferior.png",
            "[VIC]": "icon_discipline_vicissitude_superior.png",
            "[vis]": "icon_discipline_visceratika_inferior.png",
            "[VIS]": "icon_discipline_visceratika_superior.png",

            // Clans
            "[ahr]": "icon_clan_ahrimanes.png",
            "[aku]": "icon_clan_akunanse.png",
            "[and]": "icon_clan_anda.png",
            "[ass]": "icon_clan_assamite.png",
            "[baa]": "icon_clan_baali.png",
            "[ban]": "icon_clan_banu_haqim.png", 
            "[blo]": "icon_clan_blood_brothers.png",
            "[bru]": "icon_clan_brujah.png",
            "[!bru]": "icon_clan_brujah_antitribu.png",
            "[cai]": "icon_clan_caitiff.png",
            "[cap]": "icon_clan_cappadocian.png",
            "[dau]": "icon_clan_daughters_of_cacophony.png",
            "[fol]": "icon_clan_followers_of_set.png",
            "[gan]": "icon_clan_gangrel.png",
            "[!gan]": "icon_clan_gangrel_antitribu.png",
            "[gar]": "icon_clan_gargoyles.png",
            "[gio]": "icon_clan_giovanni.png",
            "[gur]": "icon_clan_guruhi.png",
            "[hec]": "icon_clan_hecata.png",
            "[har]": "icon_clan_harbringers_of_skulls.png",
            "[ish]": "icon_clan_isharri.png",
            "[kia]": "icon_clan_kiasyd.png",
            "[kin]": "icon_clan_kinyonyi.png",
            "[lam]": "icon_clan_lamia.png",
            "[las]": "icon_clan_lasombra.png",
            "[mal]": "icon_clan_malkavian.png",
            "[!mal]": "icon_clan_malkavian_antitribu.png",
            "[min]": "icon_clan_ministry.png",
            "[nag]": "icon_clan_nagaraja.png",
            "[nal]": "icon_clan_nagloper.png",
            "[noi]": "icon_clan_noiad.png",
            "[nos]": "icon_clan_nosferatu.png",
            "[!nos]": "icon_clan_nosferatu_antitribu.png",
            "[ose]": "icon_clan_osebo.png",
            "[pan]": "icon_clan_pander.png",
            "[rav]": "icon_clan_ravnos.png",
            "[sal]": "icon_clan_salubri.png",
            "[!sal]": "icon_clan_salubri_antitribu.png",
            "[sam]": "icon_clan_samedi.png",
            "[tor]": "icon_clan_toreador.png",
            "[!tor]": "icon_clan_toreador_antitribu.png",
            "[tre]": "icon_clan_tremere.png",
            "[!tre]": "icon_clan_tremere_antitribu.png",
            "[tru]": "icon_clan_true_brujah.png",
            "[tzi]": "icon_clan_tzimisce.png",
            "[ven]": "icon_clan_ventrue.png",
            "[!ven]": "icon_clan_ventrue_antitribu.png",
            "[vol]": "icon_clan_volgirre.png"
        },
    };

    // END datatables & maps